// bsp2obj.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include "BSP.h"
#include "VFS/VFS.h"

#include <direct.h> // TODO remove me

#include <vector>
#include <iostream>
#include <fstream>
#include <string>

#include <assert.h>

using namespace std;

#define VERBOSE( x )	

bool ReadWholeFile( const char* file, vector<uint8_t>& data )
{
	FILE* f;
	fopen_s( &f, file, "rb" );
	if ( !f )
		return false;

	fseek( f, 0, SEEK_END );
	data.resize( ftell( f ) );
	fseek( f, 0, SEEK_SET );

	size_t totalRead = 0;
	while ( !feof( f ) && totalRead < data.size() )
	{
		size_t r = fread( &data[totalRead], 1, data.size() - totalRead, f );
		if ( !r )
			break;
		totalRead += r;
	}

	fclose(f);

	data.resize( totalRead );

	return true;
}

std::string SafeF( float f )
{
	char tmp[128];
	sprintf_s(
		tmp, sizeof(tmp),
		"%f", f );
	return tmp;
}

std::string SafeMaterial( std::string mtl )
{
    for ( size_t i = 0; i < mtl.size(); ++i )
    {
        if ( mtl[i] == '/' )
            mtl[i] = '_';
    }
    return std::move( mtl );
}

const int SF_NODRAW = 0x00200000;


bool DumpObj( const char* filename, const char* mtlFilename, const BSP* bsp )
{
	// Open the output file
	ofstream obj;
	obj.open( filename );
	if ( !obj.is_open() )
	{
		cout << "FAILED to write!" << endl;
		delete bsp;
		return false;
	}

	obj.unsetf(ostream::floatfield);

	obj << "# Generated by BSP2OBJ" << endl;
	obj << "# BSP2OBJ was created by Peter J. B. Lewis, 2013" << endl;
	obj << "# If your OBJ doesn't load, please email the " << endl;
	obj << "# dedicated support email: bsp2obj@gibbering.net" << endl;
	obj << endl;

    std::string localMtlFN = mtlFilename;
    std::string::size_type slashPos = localMtlFN.find('/');
    if ( slashPos != std::string::npos )
    {
        localMtlFN = localMtlFN.substr(slashPos + 1);
    }
    obj << "mtllib " << localMtlFN.c_str() << endl << endl;

	obj << "# Begin Vertex Positions for " << bsp->Vertices.size() << " vertices." << endl;
	for ( auto& v : bsp->Vertices )
	{
		obj << "v " << SafeF( v.Position[0] )
			<<  " " << SafeF( v.Position[1] )
			<<  " " << SafeF( v.Position[2]	)
			<< endl;
	}
	obj << "# End Vertex Positions" << endl << endl;

	obj << "# Begin Vertex UVs for " << bsp->Vertices.size() << " vertices." << endl;
	for ( auto& v : bsp->Vertices )
	{
		obj << "vt " << SafeF( v.TexCoord[0] )
			<<   " " << SafeF( v.TexCoord[1] )
			<<   " " << SafeF( v.TexCoord[2] )
			<< endl;
	}
	obj << "# End Vertex UVs" << endl << endl;

	obj << "# Begin Vertex Normals for " << bsp->Vertices.size() << " vertices." << endl;
	for ( auto& v : bsp->Vertices )
	{
		obj << "vn " << SafeF( v.Normal[0] )
			<<   " " << SafeF( v.Normal[1] )
			<<   " " << SafeF( v.Normal[2] )
			<< endl;
	}
	obj << "# End Vertex Normals" << endl << endl;

	obj << "# Begin Face Definitions for " << bsp->Faces.size() << " faces." << endl;
    int surfCount = 0;
	for ( auto& f : bsp->Faces )
	{
        if ( f.NumIndices == 0 )
            continue;

        // Skip non-solid surfs
		const BSP::Texture& tex = bsp->Materials[f.TextureID];
        if ( tex.Flags & SF_NODRAW )
            continue;

        obj << "usemtl " << SafeMaterial( tex.Name ) << endl;
        obj << "o surf" << surfCount << endl;

		const uint32_t* indices = &bsp->Indices[f.StartIndex];
        
        surfCount++;

		int numFaces = f.NumIndices / 3;
		for ( int a = 0; a < numFaces; ++a )
		{
			size_t i = 1 + f.StartVertexIndex + indices[a * 3 + 0];
			size_t j = 1 + f.StartVertexIndex + indices[a * 3 + 1];
			size_t k = 1 + f.StartVertexIndex + indices[a * 3 + 2];
			obj << "f "	<< i << "/" << i << "/" << i << " "
						<< j << "/" << j << "/" << j << " "
						<< k << "/" << k << "/" << k << " "
						<< endl;
		}

		obj << endl;
	}
	obj << "# End Face Definitions" << endl << endl;

	VERBOSE( cout << "OK!" << endl );

	obj.close();

    return true;
}

bool DumpMtl( const char* filename, const BSP* bsp )
{
	ofstream mtl;
	mtl.open( filename );
	if ( !mtl.is_open() )
	{
		cout << "FAILED to open material file: " << filename << endl;
		delete bsp;
		return false;
	}

	mtl.unsetf(ostream::floatfield);

	mtl << "# Generated by BSP2OBJ" << endl;
	mtl << "# BSP2OBJ was created by Peter J. B. Lewis, 2013" << endl;
	mtl << "# If your OBJ doesn't load, please email the " << endl;
	mtl << "# dedicated support email: bsp2obj@gibbering.net" << endl;
	mtl << endl;

    for ( auto& tex : bsp->Materials )
    {
        // Skip non-solid surfs
        if ( tex.Flags & SF_NODRAW )
            continue;

        mtl << "newmtl " << SafeMaterial( tex.Name ) << endl;
        mtl << "Ka 1 1 1" << endl;
        mtl << "Kd 1 1 1" << endl;
        mtl << "Ks 0 0 0" << endl;
        mtl << "Ns 10" << endl;
        mtl << "map_Kd " << tex.Name << endl;
        mtl << endl;
    }

	mtl.close();

    return true;
}

void MountPakFiles()
{
	// Enumerate the pak files
	VFS::FileListing files;
	VFS::FileListing pakFiles;

	VFS::EnumerateFiles( 
		"/",
		files, 
		true );
	for ( auto& f : files )
	{
		if ( f.find(".pk3") != std::string::npos )
		{
			pakFiles.insert(f);
		}
	}

	for ( auto& f : pakFiles )
	{
		cout << "Mounting " << f << endl;

		VFS::AddZip( f.c_str(), true );
	}
}

int _tmain(int argc, _TCHAR* argv[])
{
	if ( argc < 2 )
		VFS::SetRootDirectory( _getcwd( NULL, 0 ) );
	else
		VFS::SetRootDirectory( argv[1] );

	MountPakFiles();

	VFS::FileListing gameFiles;
	VFS::FileListing bspFiles;
	VFS::EnumerateFiles(
		"/",
		gameFiles );
	for ( auto& f : gameFiles )
	{
		if ( f.find(".bsp") != std::string::npos )
			bspFiles.insert( f );
	}

	cout << "Found " << bspFiles.size() << " BSP files in " << gameFiles.size() << " game files." << endl;

	return 0;
















	vector<uint8_t> bspData;

	if ( argc < 3 )
	{
		VERBOSE( cout << "Usage: bsp2obj <input.bsp> <output.obj>" << endl );
		return 1;
	}

	cout << "BSP2OBJ " << argv[1] << " ... ";

	if ( !ReadWholeFile( argv[1], bspData ) )
	{
		cout << "FAILED" << endl; 
		return 1;
	}

	VERBOSE( cout << "OK! " << bspData.size() << " bytes read." << endl );
	VERBOSE( cout << "Parsing ... " );

	BSP* bsp = BSP::Create( &bspData[0], bspData.size() );
	if ( !bsp )
	{
		cout << "FAILED" << endl;
		return 1;
	}

	VERBOSE( cout << "OK!" << endl );
	VERBOSE( cout << "Summary:" << endl );

	VERBOSE( cout << " * " << bsp->Materials.size() << " Materials" << endl );
	VERBOSE( cout << " * " << bsp->Planes.size() << " Planes" << endl );
	VERBOSE( cout << " * " << bsp->Nodes.size() << " Nodes" << endl );
	VERBOSE( cout << " * " << bsp->Leaves.size() << " Leaves" << endl );
	VERBOSE( cout << " * " << bsp->LeafFaces.size() << " Leaf Faces" << endl );
	VERBOSE( cout << " * " << bsp->LeafBrushes.size() << " Leaf Brushes" << endl );
	VERBOSE( cout << " * " << bsp->Models.size() << " Models" << endl );
	VERBOSE( cout << " * " << bsp->Brushes.size() << " Brushes" << endl );
	VERBOSE( cout << " * " << bsp->BrushSides.size() << " Brush Sides" << endl );
	VERBOSE( cout << " * " << bsp->Vertices.size() << " Vertices" << endl );
	VERBOSE( cout << " * " << bsp->Indices.size() << " Indices" << endl );
	VERBOSE( cout << " * " << bsp->Fogs.size() << " Fogs" << endl );
	VERBOSE( cout << " * " << bsp->Faces.size() << " Faces" << endl );
	VERBOSE( cout << " * " << bsp->LightMaps.size() << " Light Maps" << endl );
	VERBOSE( cout << " * " << bsp->LightVolumes.size() << " Light Volumes" << endl );
	VERBOSE( cout << " * " << bsp->NumClusters << " Clusters" << endl );

	VERBOSE( cout << "Saving to " << argv[2] < " ... " );

	// Open the material definition file
	std::string mtlFile = argv[2];
	mtlFile = mtlFile.substr( 0, mtlFile.find_last_of('.') );
	mtlFile += ".mtl";

    int result = 1;
    if ( DumpObj( argv[2], mtlFile.c_str(), bsp ) )
    {
	    if ( DumpMtl( mtlFile.c_str(), bsp ) )
            result = 0;
    }

    delete bsp;

    if ( result == 0 )
        cout << "OK!" << endl;

	return result;
}

